from .OrigenDeGeneracion import *
from .ClasificacionSismo import *
from .MagnitudRichter import *
from .AlcanceSismo import *
from .EstadosEventoSismico.EstadoEventoSismico import *
from .TipoDeDato import *
from .EstacionSismologica import *
from .Empleado import *
from .Usuario import *
from .CambioEstado import *
from .DetalleMuestraSismica import *
from .MuestraSismica import *
from .SerieTemporal import *
from .Sismografo import *
from .EventoSismico import *
from .Sesion import *
from .Estado import *
