# Generated by Django 5.2.1 on 2025-10-29 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlcanceSismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionSismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kmProfundidadDesde', models.FloatField()),
                ('kmProfundidadHasta', models.FloatField()),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMuestraSismica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('apellido', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstacionSismologica',
            fields=[
                ('codigoEstacion', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('documentoCertificacionAdq', models.TextField()),
                ('fechaSolicitudCertificacion', models.DateTimeField(blank=True, null=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('nombre', models.CharField(max_length=100)),
                ('nroCertificacionAdquisicion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('ambito', models.CharField(max_length=100)),
                ('nombreEstado', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MagnitudRichter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionMagnitud', models.CharField(max_length=200)),
                ('numero', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrigenDeGeneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeDato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=100)),
                ('nombreUnidadMedida', models.CharField(max_length=100)),
                ('valorUmbral', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('contrasenia', models.CharField(max_length=100)),
                ('nombreUsuario', models.CharField(max_length=100)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Main.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraInicio', models.DateTimeField(blank=True, null=True)),
                ('fechaHoraFin', models.DateTimeField(blank=True, null=True)),
                ('responsableInspeccion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.empleado')),
                ('estado', models.ForeignKey(db_column='estado_nombreEstado', on_delete=django.db.models.deletion.CASCADE, to='Main.estado')),
            ],
        ),
        migrations.CreateModel(
            name='MuestraSismica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraMuestra', models.DateTimeField(blank=True, null=True)),
                ('detalleMuestraSismica', models.ManyToManyField(to='Main.detallemuestrasismica')),
            ],
        ),
        migrations.CreateModel(
            name='SerieTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicionAlarma', models.CharField(max_length=200)),
                ('fechaHoraInicioRegistroMuestras', models.DateTimeField(blank=True, null=True)),
                ('fechaHoraRegistros', models.DateTimeField(blank=True, null=True)),
                ('frecuenciaMuestreo', models.FloatField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.estado')),
                ('muestraSismica', models.ManyToManyField(to='Main.muestrasismica')),
            ],
        ),
        migrations.CreateModel(
            name='EventoSismico',
            fields=[
                ('fechaHoraFin', models.DateTimeField(blank=True, null=True)),
                ('fechaHoraOcurrencia', models.DateTimeField(blank=True, null=True)),
                ('idCompuesto', models.CharField(editable=False, max_length=1000, primary_key=True, serialize=False)),
                ('latitudEpicentro', models.FloatField()),
                ('longitudEpicentro', models.FloatField()),
                ('latitudHipocentro', models.FloatField()),
                ('longitudHipocentro', models.FloatField()),
                ('alcanceSismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.alcancesismo')),
                ('cambiosEstado', models.ManyToManyField(to='Main.cambioestado')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.clasificacionsismo')),
                ('estadoActual', models.ForeignKey(db_column='estado_nombreEstado', on_delete=django.db.models.deletion.CASCADE, related_name='eventos_actuales', to='Main.estado')),
                ('magnitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.magnitudrichter')),
                ('origenGeneracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.origendegeneracion')),
                ('serieTemporal', models.ManyToManyField(to='Main.serietemporal')),
            ],
        ),
        migrations.CreateModel(
            name='Sismografo',
            fields=[
                ('fechaAdquisicion', models.DateTimeField(blank=True, null=True)),
                ('identificadorSismografo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nroSerie', models.CharField(max_length=100)),
                ('estacionSismologica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.estacionsismologica')),
                ('serieTemporal', models.ManyToManyField(to='Main.serietemporal')),
            ],
        ),
        migrations.AddField(
            model_name='detallemuestrasismica',
            name='tipoDeDato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.tipodedato'),
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Main.usuario')),
                ('fechaInicio', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
