# Generated by Django 5.2.1 on 2025-05-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambioestado',
            name='fechaHoraInicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estacionsismologica',
            name='fechaSolicitudCertificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventosismico',
            name='fechaHoraOcurrencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muestrasismica',
            name='fechaHoraMuestra',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serietemporal',
            name='fechaHoraInicioRegistroMuestras',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serietemporal',
            name='fechaHoraRegistros',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='fechaInicio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sismografo',
            name='fechaAdquisicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
