# Generated by Django 5.2.1 on 2025-10-29 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cambioestado',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='ambito',
        ),
        migrations.RemoveField(
            model_name='eventosismico',
            name='estadoActual',
        ),
        migrations.RemoveField(
            model_name='serietemporal',
            name='estado',
        ),
        migrations.CreateModel(
            name='Autodetectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='Main.estado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BloqueadoEnRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='Main.estado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Confirmado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='Main.estado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
