# Generated by Django 5.2.1 on 2025-11-05 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_remove_cambioestado_estado_remove_estado_ambito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloqueadoenrevision',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='confirmado',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cambioestado',
            name='estado',
            field=models.ForeignKey(db_column='estado_nombreEstado', default='Autodetectado', on_delete=django.db.models.deletion.CASCADE, to='Main.estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estado',
            name='ambito',
            field=models.CharField(default='EventoSismico', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventosismico',
            name='estadoActual',
            field=models.ForeignKey(db_column='estado_nombreEstado', default='Autodetectado', on_delete=django.db.models.deletion.CASCADE, related_name='eventos_actuales', to='Main.estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serietemporal',
            name='estado',
            field=models.ForeignKey(default='Autodetectado', on_delete=django.db.models.deletion.CASCADE, to='Main.estado'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Autodetectado',
        ),
        migrations.DeleteModel(
            name='BloqueadoEnRevision',
        ),
        migrations.DeleteModel(
            name='Confirmado',
        ),
    ]
