# Generated by Django 5.2.1 on 2025-05-27 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_cambioestado_fechahorainicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serietemporal',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_temporales', to='Main.eventosismico'),
        ),
    ]
