# Generated by Django 5.2.1 on 2025-05-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_serietemporal_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serietemporal',
            name='evento',
        ),
        migrations.AddField(
            model_name='eventosismico',
            name='serieTemporal',
            field=models.ManyToManyField(to='Main.serietemporal'),
        ),
    ]
