# Generated by Django 5.2.1 on 2025-05-28 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_remove_detallemuestrasismica_muestra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambioestado',
            name='responsableInspeccion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.empleado'),
        ),
    ]
